default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: the_rial_news_development
  username: postgres
  password: 9999
  host: localhost
  port: 5432

test:
  <<: *default
  database: the_rial_news_test
  username: postgres
  password: 9999
  host: localhost
  port: 5432

production:
  <<: *default
  database: the_rial_news_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
